{{- $namespace := .Values.namespace -}}
{{- $env := .Values.env -}}
{{- $secretName := .Values.storage.secretName -}}
kind: Secret
apiVersion: v1
metadata:
  name: "rabbit-{{ $env }}-secret"
  namespace: {{ $namespace }}
data:
  password: {{ default "" .Values.config.rabbit.password | b64enc | quote }}
  username: {{ default "" .Values.config.rabbit.username | b64enc | quote }}
type: Opaque


---

kind: Secret
apiVersion: v1
metadata:
  name: "{{ $secretName }}-{{ $env }}"
  namespace: {{ $namespace }}

data:
  azurestorageaccountkey: {{ default "" .Values.storage.azurestorageaccountkey}}
  azurestorageaccountname: {{ default "" .Values.storage.azurestorageaccountname}}
type: Opaque
